// <auto-generated />
namespace ProdBuilder0920.DataService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class partname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(partname));
        
        string IMigrationMetadata.Id
        {
            get { return "201609211004544_partname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
