// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace ProdBuilder0920.DataService.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class seedadmin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seedadmin));
        
        string IMigrationMetadata.Id
        {
            get { return "201609201906217_seedadmin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
